# Generated by Django 5.2.6 on 2025-09-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_leaverequest_created_at_alter_employee_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
