# Generated by Django 5.2.6 on 2025-09-22 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_leaverequest_updated_at_alter_leaverequest_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='annual_leave',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='personal_leave',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='sick_leave',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
