# Generated by Django 5.2.6 on 2025-09-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_team_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='maternity_leave',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='other_leave',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='relax_leave',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'ลาพักร้อน'), ('sick', 'ลาป่วย'), ('personal', 'ลากิจ'), ('relax', 'ลาพักผ่อนพิเศษ'), ('unpaid', 'ลาไม่รับค่าตอบแทน'), ('maternity', 'ลาคลอด'), ('other', 'ลาอื่นๆ')], max_length=20),
        ),
    ]
