# Generated by Django 5.2.6 on 2025-09-23 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_auto_fix_leavebalance'),
        ('hr', '0010_backfill_leavebalance_nulls'),
    ]

    operations = [
    ]
